### ISSUE TITLE
Geometry Buffer Examples

### ISSUE THREAD

**Issue by withintheruins14** [ryanking1809/THREE.MeshLine#11]
Can you provide an example of usage with a geometry buffer? I have tried this code, but I can't figure out what's wrong

``` 
const curve = new THREE.CatmullRomCurve3(points);
const geometryBuffer = new THREE.BufferGeometry().setFromPoints(curve.getPoints(100));
const line = new MeshLine();
line.setBufferArray(geometryBuffer, () => 2);
const material = new MeshLineMaterial({ color, resolution: 5 });
return new THREE.Mesh(line.geometry, material);
```

App Error:
```
TypeError: Failed to execute 'uniform2fv' on 'WebGLRenderingContext': No function was found that matched the signature provided.
SingleUniform.setValueV2f [as setValue]
```

**Comment by ryanking1809** [comment]
I'll suss out what going on there - but unless you're doing something extra, in this case, the buffer geometry is an unnecessary step. The following should work:

```js
const curve = new THREE.CatmullRomCurve3(points);
const vertices = curve.getPoints(100);
const line = new MeshLine();
line.setVertices(vertices, () => 2);
const material = new MeshLineMaterial({ color, resolution: 5 });
return new THREE.Mesh(line, material);
```

Also, I just realised you're using `THREE.Mesh(line.geometry, material)`. In this version `line` is the `geometry` so perhaps changing it to `THREE.Mesh(line, material)` will solve the issue for you as well?

**Comment by withintheruins14** [comment]
Thanks for your help, however I am still seeing the same error with both suggestions

<img width="718" alt="Screen Shot 2020-04-27 at 9 04 03 AM" src="https://user-images.githubusercontent.com/2576699/80381425-89503c00-8866-11ea-9141-ab88717dfc0e.png">

**Comment by ryanking1809** [comment]
Ok, I'll take a look.  Potentially it could be related to this https://github.com/spite/THREE.MeshLine/issues/39 how are you setting defining your color? Could you try `let color = new THREE.Color(0xff0000)`

**Comment by ryanking1809** [comment]
Yeah, the code above (at least without the buffer geom) is working fine for me. See line 92 in this code sandbox https://codesandbox.io/s/canvas-sketch-a4-artwork-xlsto?file=/src/index.js
I suspect it may be your color?

```js
 const vertices = new THREE.CatmullRomCurve3(points).getPoints(200);
    const line = new MeshLine();
    line.setVertices(vertices);
    const geometry = line;

    lineMesh[i] = new THREE.Mesh(
      geometry,
      new MeshLineMaterial({
        lineWidth: random.range(0.029, 0.025),
        color: new THREE.Color(random.pick(pallete)),
        dashArray: 2, // always has to be the double of the line
        dashOffset: 0.2, // start the dash at zero
        depthTest: 0,
        transparent: 1,
        dashRatio: random.value() // visible length range min: 0.99, max: 0.5
      })
    );
```

**Comment by withintheruins14** [comment]
Made the color change, it was my resolution - I wasn't passing a vector2 🙈

**Comment by ryanking1809** [comment]
Haha all good!
