### ISSUE TITLE
Getting twists in the meshline

### ISSUE THREAD

**Issue by leefsmp** [ryanking1809/THREE.MeshLine#12]
Greetings! I see a strange results with the meshline, I had the same behavior with the original lib so I switched to this one hoping that it will help but still... I basically initialize all vertices to the same point v[0], then using the advance function I created an animation to have the meshline expand along a predefined path. 

The problem is that the first time it is rendered, it always right, then subsequent times I see weird twists, I even tried to completely remove the initial meshline and create a new one but still seeing same issue. Do you have any insights about what could be wrong?

First run:

<img width="521" alt="Screen Shot 2020-05-09 at 09 36 24" src="https://user-images.githubusercontent.com/4352502/81467495-40d73d80-91d9-11ea-8a4f-724f0f72d111.png">
  
Second and other runs (twists may differ but always present):

<img width="521" alt="Screen Shot 2020-05-09 at 09 36 33" src="https://user-images.githubusercontent.com/4352502/81467544-8562d900-91d9-11ea-9b78-134c6278f328.png">

**Comment by ryanking1809** [comment]
Oh that looks very strange. Is it possible to create a codesandbox demonstrating the issue?

**Comment by leefsmp** [comment]
Sorry that was just a nasty bug in my own code, while updating the meshline the path was sometimes going backward a little due to accumulated value and then forward again, which was producing that strange effect. The fact that you had no clue about it convinced me the problem was on my side. Thanks for the quick turnover!
