### ISSUE TITLE
Performance with react-spring

### ISSUE THREAD

**Issue by amcdnl** [ryanking1809/THREE.MeshLine#7]
The performance when used with react-spring is bad. Take the following example:

```
  const { fromVertices, toVertices, opacity } = useSpring({
    from: {
      fromVertices: [0, 0, 0],
      toVertices: [0, 0, 0],
      opacity: 0
    },
    to: {
      opacity: selectionOpacity,
      fromVertices: [points.from?.x, points.from?.y, points.from?.z || 0],
      toVertices: [points.to?.x, points.to?.y, points.to?.z || 0]
    },
    config: animationConfig
  });

   <mesh>
        <a.meshLine
          attach="geometry"
          vertices={interpolate(
            [fromVertices, toVertices],
            (a, b) => [
              { x: a[0], y: a[1], z: a[2] },
              { x: b[0], y: b[1], z: b[2] }
            ]
          )}
        />
        <a.meshLineMaterial
          attach="material"
          opacity={opacity}
          fog={true}
          transparent={true}
          depthTest={false}
          lineWidth={size}
          color={color}
        />
      </mesh>
```

the same code just using a normal line like:

```
  <line>
        <a.geometry
          ref={line}
          attach="geometry"
          onUpdate={self => (self.verticesNeedUpdate = true)}
          vertices={interpolate(
            [fromVertices, toVertices],
            (a, b) => [
              { x: a[0], y: a[1], z: a[2] },
              { x: b[0], y: b[1], z: b[2] }
            ]
          )}
        />
        <lineBasicMaterial name="material" color="white" />
      </line>
```

performs just fine. Any thoughts on a solution?

**Comment by ryanking1809** [comment]
Hmm I didn't write the code for `meshline` (it does look like it could be more efficient) and I would need to learn more about shaders to get it as efficient as `line`. In saying that I have had troubles getting `react-spring` to be super efficient, so I've made my own very basic spring library as a workaround https://github.com/ryanking1809/simple-spring. Also if you're only using `meshline` for raycasting, I've made another library to simply use raycasting with `line` https://github.com/ryanking1809/three-line-raycast

**Comment by amcdnl** [comment]
Got it. Thanks for your help. I ended up going with tube geometry (though I havne't figured out how to animate it yet: https://spectrum.chat/react-three-fiber/general/spring-animations-with-args-geometries~452d43d3-ecf7-4628-a05c-912d644585dd.
